# Generated by Django 3.0.6 on 2020-05-17 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquariums',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('volume_type', models.CharField(choices=[('liter', 'Liter'), ('gallon', 'Gallon')], max_length=255, verbose_name='Volume Type')),
                ('aquarium_type', models.CharField(choices=[('freshwater', 'Freshwater'), ('saltwater', 'Saltwater'), ('brackish_water', 'Brackish Water')], max_length=255, verbose_name='Aquarium Type')),
                ('length', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Length')),
                ('height', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Height')),
                ('width', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Width')),
                ('tank_volume', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tank Volume')),
                ('tank_volume_real', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tank Volume Real')),
                ('visibility', models.BooleanField(default=True, verbose_name='Visibility')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipamentTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('unit', models.CharField(max_length=5, verbose_name='Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=250, verbose_name='Brand')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('date_execution', models.DateTimeField(verbose_name='Date Execution')),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.Aquariums', verbose_name='Aquarium')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aquariums.TestTypes', verbose_name='Test Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aquariums.TestTypes', verbose_name='Test Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvolutionPhotos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('date_execution', models.DateField(verbose_name='Date Execution')),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.Aquariums', verbose_name='Aquarium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=250, verbose_name='Brand')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('value_payed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Value Payed')),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.Aquariums', verbose_name='Aquarium')),
                ('equipament_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aquariums.EquipamentTypes', verbose_name='Equipament Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aquariums',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquariums.Goals', verbose_name='Goal'),
        ),
        migrations.AddField(
            model_name='aquariums',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquariums', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
