# Generated by Django 3.0.6 on 2020-07-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='agree_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
